name: spotify-downloader

services:
  spotify-downloader:
    image: pjmeca/spotify-downloader:latest
    container_name: spotify-downloader
    build:
      context: .
      platforms:
        - linux/amd64
    volumes:
      - /your/main/music/path:/music # Change this
      - /path/to/tracking.yaml:/app/tracking.yaml:ro # Change this
      - /etc/localtime:/etc/localtime:ro
    environment:
      CRON_SCHEDULE: "0 0 * * *" # Customize your cron if needed
      #FORMAT: "opus" # Music format. Must be compatible with spotdl. Defaults to "opus".
      #OPTIONS: "--client-id <YOUR_ID> --client-secret <YOUR_SECRET> # Additional spotdl options. I like to add here my Spotify credentials.
    restart: unless-stopped
