name: spotify-downloader

services:
  spotify-downloader:
    image: pjmeca/spotify-downloader:latest
    build: ./SpotifyDownloader
    container_name: spotify-downloader
    restart: unless-stopped
    volumes:
      - ./Music:/music
      - ./tracking.yaml:/app/tracking.yaml:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      CRON_SCHEDULE: "0 0 * * *"
      CLIENT__ID: "" # Required
      CLIENT__SECRET: "" # Required
      FORMAT: "opus" # Music format. Must be compatible with spotdl. Defaults to "opus".
      OPTIONS: "" # Additional spotdl options.