name: spotify-downloader

services:
  spotify-downloader:
    image: pjmeca/spotify-downloader:latest
    build: ./SpotifyDownloader
    container_name: spotify-downloader
    restart: unless-stopped
    volumes:
      - ./Music:/music
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./tracking.yaml:/app/tracking.yaml:ro
      - ./cookies.txt:/app/cookies.txt # (Recommended) Path to your cookies.txt file
    environment:
      TZ: Europe/Madrid
      CRON_SCHEDULE: "0 0 * * *"
      CLIENT__ID: "" # Required
      CLIENT__SECRET: "" # Required
      FORMAT: "opus" # Music format. Must be compatible with spotdl. Defaults to "opus".
      OPTIONS: "--cookies /app/cookies.txt" # Additional yt-dlp options.
