site_name: pjmeca/spotify-downloader
site_url: https://spotify-downloader.pjmeca.com
copyright: Copyright &copy; 2024 - 2026 Pablo Meca
repo_url: https://github.com/pjmeca/spotify-downloader
repo_name: pjmeca/spotify-downloader

theme:
  name: material
  logo: assets/images/logo.webp
  favicon: assets/images/logo.webp
  icon:
    repo: fontawesome/brands/github
  font:
    text: Fira Mono
    code: Fira Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: custom
      accent: custom
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - toc.follow
    - toc.integrate 
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer

extra:
  generator: false
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/pjmeca/spotify-downloader
    - icon: fontawesome/brands/github
      link: https://github.com/pjmeca/spotify-downloader
    - icon: fontawesome/solid/at
      link: mailto:hello@pjmeca.com?subject=[spotify-downloader]
      name: email me!
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pjmeca/
  analytics:
    provider: google
    property: G-MWWY42S7F0
    extra:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: -1
          note: >- 
            Thanks for your feedback! Help us improve this page by
            submitting and issue on <a href="https://github.com/pjmeca/spotify-downloader/issues/new/?title=[Feedback]+{title}+-+{url}">GitHub</a>.

plugins:
  - search
  - privacy
  - awesome-nav
  - open-in-new-tab
  - optimize

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true         # use pygments library    
      pygments_style: default    # use 'default' style
      noclasses: true            # update HTML style attr
  - pymdownx.superfences         # required extension
  - pymdownx.inlinehilite        # style inline code

extra_css:
  - assets/stylesheets/custom-color.css

# TODO
# - cookies
# - social cards
# - versioning
# - code actions
# - revisioning
